# Generated by Django 3.0.5 on 2020-05-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dict',
            options={'verbose_name': '字典', 'verbose_name_plural': '字典'},
        ),
        migrations.AlterModelOptions(
            name='dicttype',
            options={'verbose_name': '字典类型', 'verbose_name_plural': '字典类型'},
        ),
        migrations.AlterField(
            model_name='permission',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='方法/代号'),
        ),
    ]
