# Generated by Django 3.1.7 on 2021-07-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='方法/代号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
