# Generated by Django 3.1.8 on 2022-02-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210718_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='depts',
            field=models.ManyToManyField(blank=True, related_name='roles', to='system.Organization', verbose_name='权限范围'),
        ),
    ]
