# Generated by Django 3.0.5 on 2020-07-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200615_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='fullname',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='全名'),
        ),
        migrations.AddField(
            model_name='dict',
            name='is_used',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='historicaldict',
            name='fullname',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='全名'),
        ),
        migrations.AddField(
            model_name='historicaldict',
            name='is_used',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='文件格式'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterUniqueTogether(
            name='dict',
            unique_together={('name', 'is_used', 'type')},
        ),
    ]
