# Generated by Django 3.0.5 on 2020-12-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200724_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='historicaldict',
            name='fullname',
        ),
    ]
