# Generated by Django 4.2.8 on 2024-03-24 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, help_text="修改时间", verbose_name="修改时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="删除标记", verbose_name="删除标记"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, unique=True, verbose_name="课程标题"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("公开课", "公开课"), ("入门课", "入门课"), ("进阶课", "进阶课")],
                        default="公开课",
                        max_length=128,
                        verbose_name="课程类型",
                    ),
                ),
                ("lesson_count", models.IntegerField(verbose_name="课程数量")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
