# Generated by Django 4.2.8 on 2024-03-24 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ftz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, help_text="修改时间", verbose_name="修改时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="删除标记", verbose_name="删除标记"
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="课时标题")),
                (
                    "type",
                    models.CharField(
                        choices=[("编程课", "编程课"), ("编程卡", "编程卡")],
                        default="编程课",
                        max_length=128,
                        verbose_name="课程类型",
                    ),
                ),
                (
                    "group",
                    models.CharField(default="默认分组", max_length=128, verbose_name="分组"),
                ),
                (
                    "status",
                    models.IntegerField(choices=[], default=0, verbose_name="状态"),
                ),
                (
                    "card_core_image",
                    models.CharField(blank=True, max_length=128, verbose_name="核心图"),
                ),
                (
                    "topic",
                    models.CharField(blank=True, max_length=128, verbose_name="话题"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "简单"), ("medium", "中等"), ("difficult", "困难")],
                        default="easy",
                        max_length=32,
                        verbose_name="难度",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, help_text="修改时间", verbose_name="修改时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="删除标记", verbose_name="删除标记"
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="课时标题")),
                (
                    "type",
                    models.CharField(
                        choices=[("编程课", "编程课"), ("编程卡", "编程卡")],
                        default="编程课",
                        max_length=128,
                        verbose_name="课程类型",
                    ),
                ),
                ("lesson_number", models.IntegerField(verbose_name="顺序")),
                ("version", models.CharField(verbose_name="版本号")),
                (
                    "group",
                    models.CharField(default="默认分组", max_length=128, verbose_name="分组"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, help_text="修改时间", verbose_name="修改时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="删除标记", verbose_name="删除标记"
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="标题")),
                (
                    "sub_title",
                    models.CharField(blank=True, max_length=512, verbose_name="副标题"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("QNA", "问卷页"),
                            ("Article", "图文内容页"),
                            ("TrueFalse", "判断题页"),
                        ],
                        max_length=128,
                        verbose_name="课程类型",
                    ),
                ),
                ("context", models.TextField(verbose_name="素材内容")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
