# Generated by Django 3.2.12 on 2023-03-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='filter_dept',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='部门字段过滤'),
        ),
    ]
